from pathlib import Path
p=Path('/home/ubuntu/hofong-portfolio/client/src/pages/Home.tsx')
s=p.read_text()
# Add editable copy fields to the content model.
s=s.replace('''type SiteContent = {\n  heroEyebrow: string;''','''type SiteContent = {\n  profileKicker: string;\n  profileTitle: string;\n  profileBody1: string;\n  profileBody2: string;\n  timelineKicker: string;\n  timelineTitle: string;\n  timelineDescription: string;\n  workKicker: string;\n  workTitle: string;\n  workDescription: string;\n  heroEyebrow: string;''')
s=s.replace('''const DEFAULT_CONTENT: SiteContent = {\n  heroEyebrow:''','''const DEFAULT_CONTENT: SiteContent = {\n  profileKicker: "01 / PROFILE",\n  profileTitle: "在物質與螢幕之間，\\n保留人的尺度。",\n  profileBody1: "我相信好的設計不是把答案做得更複雜，而是讓人更容易感受到事情的本質。我的工作往返於空間設計、介面原型與田野研究，關注物件如何與記憶、行為和環境產生關係。",\n  profileBody2: "目前以台北為基地，和建築師、藝術家與開發團隊合作，將抽象的問題轉化為具體、可被使用的作品。",\n  timelineKicker: "03 / PATH & PRACTICE",\n  timelineTitle: "一路上，\\n保持好奇。",\n  timelineDescription: "學習、工作與展覽不是履歷上的標記，而是我持續更新方法的方式。",\n  workKicker: "02 / SELECTED WORK",\n  workTitle: "被使用的想法，\\n才算完成。",\n  workDescription: "選入三個關於空間、記憶與互動的實驗。每個作品都從一個問題出發，最後回到人的感受。",\n  heroEyebrow:''')
# Replace public copy blocks.
s=s.replace('''<div className="section-kicker">01 / PROFILE</div>''','''<div className="section-kicker">{content.profileKicker}</div>''',1)
s=s.replace('''<h2>在物質與螢幕之間，<em>保留人的尺度。</em></h2>\n              <div className="intro-text"><p>我相信好的設計不是把答案做得更複雜，而是讓人更容易感受到事情的本質。我的工作往返於空間設計、介面原型與田野研究，關注物件如何與記憶、行為和環境產生關係。</p><p>目前以台北為基地，和建築師、藝術家與開發團隊合作，將抽象的問題轉化為具體、可被使用的作品。</p>''','''<h2 className="editable-copy">{content.profileTitle}</h2>\n              <div className="intro-text"><p>{content.profileBody1}</p><p>{content.profileBody2}</p>''')
s=s.replace('''<div className="section-kicker">03 / PATH & PRACTICE</div><div className="section-head compact"><h2>一路上，<em>保持好奇。</em></h2><p>學習、工作與展覽不是履歷上的標記，而是我持續更新方法的方式。</p></div>''','''<div className="section-kicker">{content.timelineKicker}</div><div className="section-head compact"><h2 className="editable-copy">{content.timelineTitle}</h2><p>{content.timelineDescription}</p></div>''')
s=s.replace('''<div className="section-kicker">02 / SELECTED WORK</div><h2>被使用的想法，<br /><em>才算完成。</em></h2></div><p>選入三個關於空間、記憶與互動的實驗。每個作品都從一個問題出發，最後回到人的感受。</p>''','''<div className="section-kicker">{content.workKicker}</div><h2 className="editable-copy">{content.workTitle}</h2></div><p>{content.workDescription}</p>''')
# Add a first editor card in the same order as the public sections.
needle='''<div className="admin-heading"><div><div className="section-kicker">CONTENT / 01</div><h2>你的數位身份</h2></div><span className="saved-chip"><Check size={14} /> Autosave local</span></div>'''
editor='''<div className="admin-heading"><div><div className="section-kicker">CONTENT / 01</div><h2>你的數位身份</h2></div><span className="saved-chip"><Check size={14} /> Autosave local</span></div><section className="editor-card" id="admin-home-copy"><div className="editor-card-head"><div><span className="card-number">01</span><h3>首頁文字</h3></div><span>PUBLIC / COPY</span></div><div className="admin-subhead">關於</div><input value={draft.profileKicker} placeholder="區塊標籤" onChange={(event) => setDraft((previous) => ({ ...previous, profileKicker: event.target.value }))} /><textarea value={draft.profileTitle} rows={2} placeholder="關於標題" onChange={(event) => setDraft((previous) => ({ ...previous, profileTitle: event.target.value }))} /><textarea value={draft.profileBody1} rows={4} placeholder="關於第一段" onChange={(event) => setDraft((previous) => ({ ...previous, profileBody1: event.target.value }))} /><textarea value={draft.profileBody2} rows={3} placeholder="關於第二段" onChange={(event) => setDraft((previous) => ({ ...previous, profileBody2: event.target.value }))} /><div className="admin-subhead">經歷區塊標題</div><input value={draft.timelineKicker} placeholder="區塊標籤" onChange={(event) => setDraft((previous) => ({ ...previous, timelineKicker: event.target.value }))} /><textarea value={draft.timelineTitle} rows={2} placeholder="經歷標題" onChange={(event) => setDraft((previous) => ({ ...previous, timelineTitle: event.target.value }))} /><textarea value={draft.timelineDescription} rows={3} placeholder="經歷說明" onChange={(event) => setDraft((previous) => ({ ...previous, timelineDescription: event.target.value }))} /><div className="admin-subhead">作品集區塊標題</div><input value={draft.workKicker} placeholder="區塊標籤" onChange={(event) => setDraft((previous) => ({ ...previous, workKicker: event.target.value }))} /><textarea value={draft.workTitle} rows={2} placeholder="作品集標題" onChange={(event) => setDraft((previous) => ({ ...previous, workTitle: event.target.value }))} /><textarea value={draft.workDescription} rows={3} placeholder="作品集說明" onChange={(event) => setDraft((previous) => ({ ...previous, workDescription: event.target.value }))} /></section>'''
if needle not in s: raise SystemExit('admin heading anchor missing')
s=s.replace(needle,editor,1)
p.write_text(s)
css=Path('/home/ubuntu/hofong-portfolio/client/src/index.css')
c=css.read_text()
if '.editable-copy' not in c:
    c += '''\n.editable-copy { white-space: pre-line; }.admin-subhead { margin-top:18px; }\n'''
css.write_text(c)
