from pathlib import Path
p=Path('/home/ubuntu/hofong-portfolio/client/src/pages/Home.tsx')
s=p.read_text()
old='''<input value={project.title} onChange={(event) => setDraft((previous) => ({ ...previous, projects: previous.projects.map((item) => item.id === project.id ? { ...item, title: event.target.value } : item) }))} /><textarea value={project.description} onChange={(event) => setDraft((previous) => ({ ...previous, projects: previous.projects.map((item) => item.id === project.id ? { ...item, description: event.target.value } : item) }))} rows={2} /><div className="asset-editor">'''
new='''<input value={project.title} onChange={(event) => setDraft((previous) => ({ ...previous, projects: previous.projects.map((item) => item.id === project.id ? { ...item, title: event.target.value } : item) }))} /><div className="field-grid compact-fields"><select value={project.category} onChange={(event) => setDraft((previous) => ({ ...previous, projects: previous.projects.map((item) => item.id === project.id ? { ...item, category: event.target.value as Exclude<Category, "全部"> } : item) }))}><option>建築圖面</option><option>互動體驗</option><option>研究實作</option></select><input value={project.year} onChange={(event) => setDraft((previous) => ({ ...previous, projects: previous.projects.map((item) => item.id === project.id ? { ...item, year: event.target.value } : item) }))} placeholder="年份" /></div><input value={project.role} onChange={(event) => setDraft((previous) => ({ ...previous, projects: previous.projects.map((item) => item.id === project.id ? { ...item, role: event.target.value } : item) }))} placeholder="個人角色／負責範圍" /><textarea value={project.description} onChange={(event) => setDraft((previous) => ({ ...previous, projects: previous.projects.map((item) => item.id === project.id ? { ...item, description: event.target.value } : item) }))} rows={2} /><div className="asset-editor">'''
if old not in s: raise SystemExit('project field anchor not found')
s=s.replace(old,new)
old2='''<span>PDF 檔名或網址（可留白）</span><input value={project.pdfFile || project.pdf || ""} placeholder="case-study.pdf" onChange={(event) => setDraft((previous) => ({ ...previous, projects: previous.projects.map((item) => item.id === project.id ? { ...item, pdfFile: event.target.value, pdf: event.target.value ? assetUrl(event.target.value) : "" } : item) }))} /></div><div className="tag-list">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div>'''
new2='''<span>PDF 檔名或網址（可留白）</span><input value={project.pdfFile || project.pdf || ""} placeholder="case-study.pdf" onChange={(event) => setDraft((previous) => ({ ...previous, projects: previous.projects.map((item) => item.id === project.id ? { ...item, pdfFile: event.target.value, pdf: event.target.value ? assetUrl(event.target.value) : "" } : item) }))} /><span>外部連結（可留白）</span><input value={project.link || ""} placeholder="https://..." onChange={(event) => setDraft((previous) => ({ ...previous, projects: previous.projects.map((item) => item.id === project.id ? { ...item, link: event.target.value } : item) }))} /><span>技能標籤（逗號分隔）</span><input value={project.tags.join(", ")} onChange={(event) => setDraft((previous) => ({ ...previous, projects: previous.projects.map((item) => item.id === project.id ? { ...item, tags: event.target.value.split(",").map((tag) => tag.trim()).filter(Boolean) } : item) }))} /></div><div className="tag-list">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div>'''
if old2 not in s: raise SystemExit('asset field anchor not found')
s=s.replace(old2,new2)
# Allow new project to start with an editable PDF field and link field through a simple extra form.
old3='''<textarea value={newProject.description} onChange={(event) => setNewProject((previous) => ({ ...previous, description: event.target.value }))} placeholder="一句話作品簡介" rows={2} /><button className="button button-outline" onClick={addProject}>建立作品草稿 <Plus size={15} /></button>'''
new3='''<textarea value={newProject.description} onChange={(event) => setNewProject((previous) => ({ ...previous, description: event.target.value }))} placeholder="一句話作品簡介" rows={2} /><p className="helper-copy">作品建立後，可在上方編輯照片檔名、PDF 檔名、角色、年份、標籤與外部連結。</p><button className="button button-outline" onClick={addProject}>建立作品草稿 <Plus size={15} /></button>'''
if old3 not in s: raise SystemExit('new project anchor not found')
s=s.replace(old3,new3)
p.write_text(s)

css=Path('/home/ubuntu/hofong-portfolio/client/src/index.css')
c=css.read_text()
c += '''\n.compact-fields { margin: 7px 0; gap: 7px; }.compact-fields input, .compact-fields select { margin: 0; padding: 7px 8px; font-size: 10px; }.helper-copy { color: var(--muted); font-size: 10px; margin: 8px 0 12px; }\n'''
css.write_text(c)
